version: 2.1

orbs:
  android: circleci/android@2.4.0

jobs:
  build:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2024.01.1
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests Module Movie
          command: ./gradlew :features:movie:testDebugUnitTest
      - run:
          name: Run Tests Module Search
          command: ./gradlew :features:search:testDebugUnitTest
      - run:
          name: Run Tests Module Favorite
          command: ./gradlew :features:favorite:testDebugUnitTest
      - store_test_results:
          path: features/movie/build/test-results
      - store_test_results:
          path: features/search/build/test-results
      - store_test_results:
          path: features/favorite/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file